// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: idempotency_key.sql

package db

import (
	"context"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET response_body = $3
WHERE owner = $1 AND key = $2
RETURNING owner, key, request_hash, response_body, created_at
`

type CompleteIdempotencyKeyParams struct {
	Owner        string `json:"owner"`
	Key          string `json:"key"`
	ResponseBody string `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, completeIdempotencyKey, arg.Owner, arg.Key, arg.ResponseBody)
	var i IdempotencyKey
	err := row.Scan(
		&i.Owner,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
  owner, key, request_hash
) VALUES (
  $1, $2, $3
) RETURNING owner, key, request_hash, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	Owner       string `json:"owner"`
	Key         string `json:"key"`
	RequestHash string `json:"request_hash"`
}

// Claims the key. The primary key on (owner, key) is what makes this the mutual
// exclusion: a second concurrent request carrying the same key blocks here until the
// first transaction commits, then fails with a unique violation.
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyKey, arg.Owner, arg.Key, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.Owner,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT owner, key, request_hash, response_body, created_at FROM idempotency_keys
WHERE owner = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	Owner string `json:"owner"`
	Key   string `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.Owner, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Owner,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
